title: Services
intro: Our customers are very important to us. We show true dedication to
  meeting their exact needs, and this is what keeps them returning to us for
  Plumbing & Heating work time and time again.
plumbing_services:
  - text: GENERAL PLUMBING INSTALLATIONS
  - text: PLUMBING REPAIRS
  - text: POWER FLUSH & CHEMICAL FLUSH
  - text: RADIATORS / VALVES / THERMOSTATS INSTALLED / REPLACED
  - text: THERMOSTATIC SHOWER INSTALLATION/REPAIR
  - text: ELECTRIC SHOWER INSTALLATION
  - text: TAP REPAIR/ REPLACEMENT
  - text: SHOWER PUMP INSTALLS
  - text: COLD WATER TANK BOOSTER PUMPS
  - text: WATER SUPPLY PIPE REPAIRS
