backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: 'src/static/img'
public_folder: '/static/img'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: src/_data/home.yaml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: Intro, name: intro, widget: text }
          - { label: Featured Image, name: featured_image, widget: image }
          - label: Information Points
            name: info_points
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
          - label: Client Icons
            name: client_icons
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
          - label: About Us
            name: about
            widget: list
            fields:
              - { label: Text, name: text, widget: text }
          - label: Accreditations
            name: accreditations
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
          - label: What We Offer
            name: our_offers
            widget: list
            fields:
              - { label: Text, name: text, widget: text }
          - label: Offer Points
            name: offer_points
            widget: list
            fields:
              - { label: Text, name: text, widget: string }

      - label: 'Services Page'
        name: 'services'
        file: 'src/_data/services.yaml'
        slug: '/services'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
          - label: Plumbing Services
            name: plumbing_services
            widget: list
            fields:
              - { label: Text, name: text, widget: string }
          - label: Heating Services
            name: heating_services
            widget: list
            fields:
              - { label: Text, name: text, widget: string }

  - label: 'Settings'
    name: 'settings'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'items'
        file: 'src/_data/navigation.yaml'
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      # - label: 'Quick Links'
      #   name: 'links'
      #   file: 'src/_data/quicklinks.yaml'
      #   fields:
      #     - label: Nav Items
      #       name: links
      #       widget: list
      #       collapsed: false
      #       fields:
      #         - { label: Title, name: title, widget: string }
      #         - { label: URL, name: url, widget: string }
      #         - { label: Description, name: desc, widget: string }
      # - label: 'Meta Settings'
      #   name: 'settings'
      #   file: 'src/_data/settings.yaml'
      #   fields:
      #     - { label: Name, name: name, widget: string }
      #     - { label: Author, name: author, widget: string }
      #     - { label: URL, name: url, widget: string }

  - label: 'Blog'
    name: 'blog'
    folder: 'src/posts'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'text' }
      - widget: select
        label: 'tags'
        name: 'tags'
        multiple: true
        create: true
        options: ['Tags', 'created', 'from', 'config.yml']
