backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: 'src/static/img'
public_folder: '/static/img'

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'Home Page'
        name: 'home'
        file: src/_data/home.yaml
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string }
          - { label: Intro, name: intro, widget: text }
          - { label: Featured Image, name: featured_image, widget: image }
          - label: Information Points
            name: info_points
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Title, name: title, widget: string }
              - { label: Description, name: description, widget: text }
          - label: Client Icons
            name: client_icons
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
          - label: About Us
            name: about
            widget: list
            fields:
              - { label: Text, name: text, widget: text }
          - label: Accreditations
            name: accreditations
            widget: list
            fields:
              - { label: Image, name: image, widget: image }
          - label: What We Offer
            name: our_offers
            widget: list
            fields:
              - { label: Text, name: text, widget: text }
          - label: Offer Points
            name: offer_points
            widget: list
            fields:
              - { label: Text, name: text, widget: string }

      - label: 'Services Page'
        name: 'services'
        file: 'src/_data/services.yaml'
        slug: '/services'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
          - label: Plumbing Services
            name: plumbing_services
            widget: list
            fields:
              - { label: Text, name: text, widget: string }
          - label: Heating Services
            name: heating_services
            widget: list
            fields:
              - { label: Text, name: text, widget: string }
          - { label: Call to action, name: call_to_action, widget: text }

      - label: 'Gallery Page'
        name: 'gallery'
        file: 'src/_data/gallery.yaml'
        slug: '/gallery'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
          - label: Gallery Items
            name: gallery_items
            widget: list
            fields:
              - { label: Image, name: image, widget: image }

  - label: 'Settings'
    name: 'settings'
    files:
      - label: 'Navigation'
        name: 'items'
        file: 'src/_data/navigation.yaml'
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }

      - label: 'Footer'
        name: 'footer'
        file: 'src/_data/footer.yaml'
        fields:
          - { label: Description, name: description, type: text }
